const collectionRouter = {
    name: null,
    route: null,
    filePath: null,
    title: '藏品设置',
    type: 'folder',
    icon: 'iconfont icon-index',
    order: null,
    inNav: true,
    children: [
        {
            name: 'CreatorList',
            route: '/collection/creator',
            filePath: 'view/collection/creator.vue',
            title: '创作方',
            type: 'view',
            icon: 'iconfont icon-index',
            order: null,
            inNav: true,
        },
        {
            name: 'IssueList',
            route: '/collection/issue',
            filePath: 'view/collection/issue.vue',
            title: '发行方',
            type: 'view',
            icon: 'iconfont icon-index',
            order: null,
            inNav: true,
        },
        {
            name: 'collectionList',
            route: '/collection/collectionList',
            filePath: 'view/collection/collectionList.vue',
            title: '藏品列表',
            type: 'view',
            icon: 'iconfont icon-index',
            order: null,
            inNav: true,
        },
        {
            name: 'convertList',
            route: '/collection/convertList',
            filePath: 'view/collection/convertList.vue',
            title: '兑换卡管理',
            type: 'view',
            icon: 'iconfont icon-index',
            order: null,
            inNav: true,
        },
        {
            name: 'airDropList',
            route: '/collection/airDropList',
            filePath: 'view/collection/airDropList.vue',
            title: '空投记录',
            type: 'view',
            icon: 'iconfont icon-index',
            order: null,
            inNav: true,
        },
    ],
}

export default collectionRouter
